<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ketil B., Laurits H., Herman E. og Theodor S.">
<meta name="dcterms.date" content="2025-10-09">

<title>Effekten av styrketrening på isokinetisk kneekstensjon: En 3-ukers case-studie</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Humac_analyse_files/libs/clipboard/clipboard.min.js"></script>
<script src="Humac_analyse_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Humac_analyse_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Humac_analyse_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Humac_analyse_files/libs/quarto-html/popper.min.js"></script>
<script src="Humac_analyse_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Humac_analyse_files/libs/quarto-html/anchor.min.js"></script>
<link href="Humac_analyse_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Humac_analyse_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Humac_analyse_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Humac_analyse_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Humac_analyse_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innhold</h2>
   
  <ul>
  <li><a href="#introduksjon" id="toc-introduksjon" class="nav-link active" data-scroll-target="#introduksjon"><span class="header-section-number">1</span> Introduksjon</a></li>
  <li><a href="#metode" id="toc-metode" class="nav-link" data-scroll-target="#metode"><span class="header-section-number">2</span> Metode</a>
  <ul class="collapse">
  <li><a href="#deltakeren" id="toc-deltakeren" class="nav-link" data-scroll-target="#deltakeren"><span class="header-section-number">2.1</span> Deltakeren</a></li>
  <li><a href="#standardisering-og-familiarisering" id="toc-standardisering-og-familiarisering" class="nav-link" data-scroll-target="#standardisering-og-familiarisering"><span class="header-section-number">2.2</span> Standardisering og familiarisering</a></li>
  <li><a href="#sikkerhetsprotokoll" id="toc-sikkerhetsprotokoll" class="nav-link" data-scroll-target="#sikkerhetsprotokoll"><span class="header-section-number">2.3</span> Sikkerhetsprotokoll</a></li>
  <li><a href="#testprotokoll" id="toc-testprotokoll" class="nav-link" data-scroll-target="#testprotokoll"><span class="header-section-number">2.4</span> Testprotokoll</a></li>
  <li><a href="#treningsprogrammet" id="toc-treningsprogrammet" class="nav-link" data-scroll-target="#treningsprogrammet"><span class="header-section-number">2.5</span> Treningsprogrammet</a></li>
  <li><a href="#databehandling" id="toc-databehandling" class="nav-link" data-scroll-target="#databehandling"><span class="header-section-number">2.6</span> Databehandling</a></li>
  </ul></li>
  <li><a href="#resultater" id="toc-resultater" class="nav-link" data-scroll-target="#resultater"><span class="header-section-number">3</span> Resultater</a>
  <ul class="collapse">
  <li><a href="#tabell-3-deltakerens-resultater" id="toc-tabell-3-deltakerens-resultater" class="nav-link" data-scroll-target="#tabell-3-deltakerens-resultater"><span class="header-section-number">3.1</span> Tabell 3: Deltakerens resultater</a></li>
  <li><a href="#figur-1-linjediagram-av-resultatene-fra-tabell-1" id="toc-figur-1-linjediagram-av-resultatene-fra-tabell-1" class="nav-link" data-scroll-target="#figur-1-linjediagram-av-resultatene-fra-tabell-1"><span class="header-section-number">3.2</span> Figur 1: Linjediagram av resultatene fra Tabell 1</a></li>
  <li><a href="#tabell-4-endring-fra-pre-test-til-test-6" id="toc-tabell-4-endring-fra-pre-test-til-test-6" class="nav-link" data-scroll-target="#tabell-4-endring-fra-pre-test-til-test-6"><span class="header-section-number">3.3</span> Tabell 4: Endring fra pre-test til test 6</a></li>
  <li><a href="#variasjonskoeffisient" id="toc-variasjonskoeffisient" class="nav-link" data-scroll-target="#variasjonskoeffisient"><span class="header-section-number">3.4</span> Variasjonskoeffisient</a></li>
  <li><a href="#limb-symmetry-index" id="toc-limb-symmetry-index" class="nav-link" data-scroll-target="#limb-symmetry-index"><span class="header-section-number">3.5</span> Limb symmetry index</a></li>
  </ul></li>
  <li><a href="#diskusjon" id="toc-diskusjon" class="nav-link" data-scroll-target="#diskusjon"><span class="header-section-number">4</span> Diskusjon</a>
  <ul class="collapse">
  <li><a href="#sammenheng-med-tidligere-forskning" id="toc-sammenheng-med-tidligere-forskning" class="nav-link" data-scroll-target="#sammenheng-med-tidligere-forskning"><span class="header-section-number">4.1</span> Sammenheng med tidligere forskning</a></li>
  <li><a href="#metodiske-styrker-og-begrensninger" id="toc-metodiske-styrker-og-begrensninger" class="nav-link" data-scroll-target="#metodiske-styrker-og-begrensninger"><span class="header-section-number">4.2</span> Metodiske styrker og begrensninger</a></li>
  </ul></li>
  <li><a href="#referanseliste" id="toc-referanseliste" class="nav-link" data-scroll-target="#referanseliste"><span class="header-section-number">5</span> Referanseliste</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Effekten av styrketrening på isokinetisk kneekstensjon: En 3-ukers case-studie</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ketil B., Laurits H., Herman E. og Theodor S. </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 9, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduksjon" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduksjon"><span class="header-section-number">1</span> Introduksjon</h2>
<p>Sprintsyklister er kjennetegnet ved evnen til å produsere høy kraft og akselerasjon over korte distanser (200 - 1000m), og en avgjørende faktor for prestasjon vil være maksimal kraft i kneekstensjon (Martin et al., 2007; Rønnestad et al., 2015). Vi ser også at det er en sterk sammenheng mellom prestasjon i sykkelidrett og muskelmasse i øvre lår (Dorel et al., 2005; Rønnestad et al., 2015). Det vil dermed være naturlig for en sprintsyklist å utføre trening for å øke muskelstyrken i kombinasjon med sin vanlige sykkeltrening. Styrketrening i form av progressiv motstandstrening er en effektiv metode for å øke muskelstyrke, og benyttes ofte av sprintsyklister i periodene mellom konkurransestevner (Rønnestad et al., 2015).</p>
<p>Vi ønsket å undersøke effekten av en treningsintervensjon på underekstremitetene på maksimalt dreiemoment i kneekstensorene. Gullstandarden for måling av muskelstyrke er et isokinetisk dynamometer (Stark et al., 2011), og vi benyttet HUMAC-Cybex dynamometeret (HUMAC NORM, Computer Sports Medicine Inc., USA) som måleinstrument. Med dette som bakgrunn utførte vi en case-studie av en 24 år gammel nasjonal elitesprintsyklist som var i en fase mellom konkurransestevner, og trente progressiv styrketrening av underekstremitetene i 3 uker Samtidig testet vi deltakerens maksimale dreiemoment i kneekstensjon i tre forskjellige hastigheter; 60 °/s, 120 °/s og 240 °/s.</p>
<p>Hypotesen vår er at deltakeren vil måle økt maksimalt dreiemoment i kneekstensjon etter intervensjonen, sammenlignet med pre-test.</p>
</section>
<section id="metode" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="metode"><span class="header-section-number">2</span> Metode</h2>
<section id="deltakeren" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="deltakeren"><span class="header-section-number">2.1</span> Deltakeren</h3>
<p>Deltakeren var en 24 år gammel nasjonal elitesprintsyklist (høyde: 165cm, vekt: 64 kg). Prosjektoppstart var 10 dager etter siste sykkelritt. Deltakeren hadde 3 år med erfaring som elitesprintersyklist, og trente minimalt de 10 dagene etter ritt, da deltager hadde en pause før studieoppstart. Han hadde tidligere erfaring med progressiv styrketrening, men han hadde ikke trent styrketrening på &gt; 6 måneder. Han hadde også tidligere erfaring med øvelsene som ble utført i intervensjonen.</p>
<p>Deltakeren rapporterte ingen kontraindikasjoner eller skader ved studieoppstart.</p>
</section>
<section id="standardisering-og-familiarisering" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="standardisering-og-familiarisering"><span class="header-section-number">2.2</span> Standardisering og familiarisering</h3>
<p>Deltakeren gjennomførte to tilvenningstester (16.09 og 18.09) for å redusere innflytelse av læringseffekten på resultatene (Hopkins, 2000).</p>
<p>Deltakeren utførte to tester i uken i en periode på tre uker, og vi endte opp med seks tester totalt. Testtidspunktene ble standardisert til tirsdag og torsdag hver uke, og ble utført på samme tidspunkt på døgnet for å redusere innflytelsen av døgnrytmen. Deltakerens koffein- og matinntak ble standardisert. Deltakeren utførte treningsprotokollen cirka én time etter hver test, og han hadde 48 timers restitusjon mellom hver test.</p>
</section>
<section id="sikkerhetsprotokoll" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="sikkerhetsprotokoll"><span class="header-section-number">2.3</span> Sikkerhetsprotokoll</h3>
<p>Før teststart, ble HUMAC Cybex-apparatet kalibrert og stilt inn til deltakerens antropometriske mål i henhold til ReLieF-manualen. De spesifikke innstillingene kan man finne som et separat filvedlegg i GitHub-repositoriet.</p>
<p>Testen kunne avbrytes hvis deltakeren opplevde sterkt ubehag eller smerte.</p>
</section>
<section id="testprotokoll" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="testprotokoll"><span class="header-section-number">2.4</span> Testprotokoll</h3>
<p>Oppvarmingen bestod av 10 minutter med progressiv ergometersykling. Motstanden på ergometersykelen ble styrt av deltakeren.</p>
<p>Testprotokollen vår tok utgangspunkt i “ReLieF”-protokollen. Denne protokollen har en innebygd oppvarming, og tester maksimalt dreiemoment i tre forskjellige vinkelhastigheter (60 °/s, 120 °/s og 240 °/s). Deltakeren utførte maksimal konsentrisk kneekstensjon fra 90° knefleksjon til 0° kneekstensjon. Protokollen har også en egen oppvarming og testing av maksimal isometrisk kneekstensjon, men deltakeren utførte ikke denne delen av protokollen siden vi kun ønsket å undersøke isokinetisk kneekstensjon.</p>
<section id="tabell-1-modifisert-relief-protokoll" class="level4" data-number="2.4.1">
<h4 data-number="2.4.1" class="anchored" data-anchor-id="tabell-1-modifisert-relief-protokoll"><span class="header-section-number">2.4.1</span> Tabell 1: Modifisert ReLieF protokoll</h4>
<p><em>Alle oppvarmingene og testene starter med høyre ben</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Hastighet</th>
<th>Oppvarming</th>
<th>Pause mellom oppvarming og test</th>
<th>Test</th>
<th>Pause mellom test (sekunder)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>60 °/</td>
<td>3</td>
<td>30</td>
<td>3</td>
<td>60</td>
</tr>
<tr class="even">
<td>120 °/</td>
<td>3</td>
<td>30</td>
<td>3</td>
<td>60</td>
</tr>
<tr class="odd">
<td>240 °/</td>
<td>3</td>
<td>30</td>
<td>3</td>
<td>60</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="treningsprogrammet" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="treningsprogrammet"><span class="header-section-number">2.5</span> Treningsprogrammet</h3>
<p>Oppstartstidspunktet for intervensjonen var x.09.25, x antall dager etter første pre-test (16.09.25)</p>
<p>Treningsprogrammet bestod av to ukentlige styrketreningsøkter over en 3-ukers periode, og ble gjennomført på tirsdager og torsdager. Hver økt ble utført cirka en time etter utført isokinetisk testing. Når øvre grense for repetisjonsområde ble nådd innenfor det angitte RIR målet, ble motstanden økt med 5%.</p>
<p>Tempo under utførelse av øvelsene, samt pauser mellom serier ble styrt selv av deltakeren. Alle øktene ble utført selvstendig.</p>
<section id="tabell-2-treningsprogrammet" class="level4" data-number="2.5.1">
<h4 data-number="2.5.1" class="anchored" data-anchor-id="tabell-2-treningsprogrammet"><span class="header-section-number">2.5.1</span> Tabell 2: Treningsprogrammet</h4>
<p><em>*RIR = Repetisjoner i reserve (før utmattelse)</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Øvelse</th>
<th>Serier</th>
<th>Repetisjonsområde</th>
<th>RIR*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Knebøy med stang</td>
<td>3</td>
<td>6 - 8</td>
<td>2</td>
</tr>
<tr class="even">
<td>Kneekstensjon i maskin</td>
<td>3</td>
<td>6 - 8</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Leg curl</td>
<td>3</td>
<td>6 - 8</td>
<td>3</td>
</tr>
<tr class="even">
<td>Bulgarske utfall</td>
<td>3</td>
<td>6 - 8</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Tåhev</td>
<td>3</td>
<td>6 - 8</td>
<td>3</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="databehandling" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="databehandling"><span class="header-section-number">2.6</span> Databehandling</h3>
<p>Fra hver test ble repetisjonen med høyest målt maksimale dreiemoment (Nm) brukt til statistisk analyse.</p>
<p>Databehandlingen og analysen ble utført i R (versjon 4.5.1). Datavisualiseringen ble utført ved hjelp av tidyverse- og readxl-pakken i Rstudio. Rådata fra HUMAC testene ble innhentet fra syv Excel-filer, og importert og prosessert til et “tidy” datasett ved hjelp av R-kode. Koden for prosesseringen er inkludert i Quarto-dokumentet og tilgjengelig i GitHub-repositoriet sammen med rådataene.</p>
<p><em><strong>Merk:</strong> Tilvenning fra 16.09.25 ble ekskludert fra tidy-datasettet. Denne tilvenningen brukte en annen protokoll enn de syv andre testene, og var dermed ikke sammenlignbar med test 1 til 6. Pre-test i datasettet er dermed fra 18.09.25.</em></p>
</section>
</section>
<section id="resultater" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="resultater"><span class="header-section-number">3</span> Resultater</h2>
<section id="tabell-3-deltakerens-resultater" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="tabell-3-deltakerens-resultater"><span class="header-section-number">3.1</span> Tabell 3: Deltakerens resultater</h3>
<table class="caption-top table">
<caption>Det ble utført 3 repetisjoner x 1 serie per hastighet, og tabellen viser høyeste målte dreiemoment per test.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Tidspunkt</th>
<th>Side</th>
<th>Maksimalt Nm 60°/s</th>
<th>Maksimalt Nm 120°/s</th>
<th>Maksimalt Nm 240°/s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-test</td>
<td>Høyre</td>
<td>187</td>
<td>159</td>
<td>111</td>
</tr>
<tr class="even">
<td>Pre-test</td>
<td>Venstre</td>
<td>187</td>
<td>163</td>
<td>114</td>
</tr>
<tr class="odd">
<td>Test 1</td>
<td>Høyre</td>
<td>224</td>
<td>178</td>
<td>123</td>
</tr>
<tr class="even">
<td>Test 1</td>
<td>Venstre</td>
<td>182</td>
<td>151</td>
<td>111</td>
</tr>
<tr class="odd">
<td>Test 2</td>
<td>Høyre</td>
<td>216</td>
<td>168</td>
<td>126</td>
</tr>
<tr class="even">
<td>Test 2</td>
<td>Venstre</td>
<td>174</td>
<td>156</td>
<td>108</td>
</tr>
<tr class="odd">
<td>Test 3</td>
<td>Høyre</td>
<td>207</td>
<td>163</td>
<td>117</td>
</tr>
<tr class="even">
<td>Test 3</td>
<td>Venstre</td>
<td>187</td>
<td>151</td>
<td>114</td>
</tr>
<tr class="odd">
<td>Test 4</td>
<td>Høyre</td>
<td>203</td>
<td>163</td>
<td>113</td>
</tr>
<tr class="even">
<td>Test 4</td>
<td>Venstre</td>
<td>182</td>
<td>153</td>
<td>102</td>
</tr>
<tr class="odd">
<td><strong>Test 5</strong></td>
<td>Høyre</td>
<td>218</td>
<td>175</td>
<td>118</td>
</tr>
<tr class="even">
<td><strong>Test 5</strong></td>
<td>Venstre</td>
<td>188</td>
<td>151</td>
<td>106</td>
</tr>
</tbody>
</table>
</section>
<section id="figur-1-linjediagram-av-resultatene-fra-tabell-1" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="figur-1-linjediagram-av-resultatene-fra-tabell-1"><span class="header-section-number">3.2</span> Figur 1: Linjediagram av resultatene fra Tabell 1</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Humac_analyse_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tabell-4-endring-fra-pre-test-til-test-6" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="tabell-4-endring-fra-pre-test-til-test-6"><span class="header-section-number">3.3</span> Tabell 4: Endring fra pre-test til test 6</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Hastighet</th>
<th>Side</th>
<th>Endring i Nm og %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>60°/s</td>
<td>Høyre</td>
<td>+31 (+16.6%)</td>
</tr>
<tr class="even">
<td>60°/s</td>
<td>Venstre</td>
<td>+1(0.5%)</td>
</tr>
<tr class="odd">
<td>120°/s</td>
<td>Høyre</td>
<td>+16 (+10.1%)</td>
</tr>
<tr class="even">
<td>120°/s</td>
<td>Venstre</td>
<td>-12 (-7.4%)</td>
</tr>
<tr class="odd">
<td>240°/s</td>
<td>Høyre</td>
<td>+7 (+6.3%)</td>
</tr>
<tr class="even">
<td>240°/s</td>
<td>Venstre</td>
<td>-8(-7%)</td>
</tr>
</tbody>
</table>
</section>
<section id="variasjonskoeffisient" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="variasjonskoeffisient"><span class="header-section-number">3.4</span> Variasjonskoeffisient</h3>
<p>Variasjonskoeffisienten (VK) beskriver spredningen av data relativt til gjenomsnittet (Atkinson &amp; Nevill, 1988). I vår studie kan VK være et nyttig verktøy for å vurdere konsistensen til målingene til deltakeren i maksimalt dreiemoment mellom de syv ulike testene. En lav VK (&lt;5%) vil indikere høy konsistens mellom målingene, mens en høy VK (&gt;10%) vil indikere større variasjon mellom målingene.</p>
<section id="tabell-5-variasjonskoeffisient-mellom-testene" class="level4" data-number="3.4.1">
<h4 data-number="3.4.1" class="anchored" data-anchor-id="tabell-5-variasjonskoeffisient-mellom-testene"><span class="header-section-number">3.4.1</span> Tabell 5: Variasjonskoeffisient mellom testene</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Hastighet</th>
<th>Side</th>
<th>Gjennomsnitt (Nm)</th>
<th>SD (Nm)</th>
<th>CV(%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>60°/s</td>
<td>Høyre</td>
<td>209.2</td>
<td>13.2</td>
<td>6.3</td>
</tr>
<tr class="even">
<td>60°/s</td>
<td>Venstre</td>
<td>183.3</td>
<td>5.3</td>
<td>2.9</td>
</tr>
<tr class="odd">
<td>120°/s</td>
<td>Høyre</td>
<td>167.7</td>
<td>7.5</td>
<td>4.5</td>
</tr>
<tr class="even">
<td>120°/s</td>
<td>Venstre</td>
<td>154.2</td>
<td>4.8</td>
<td>3.1</td>
</tr>
<tr class="odd">
<td>240°s</td>
<td>Høyre</td>
<td>118</td>
<td>5.7</td>
<td>4.9</td>
</tr>
<tr class="even">
<td>240°s</td>
<td>Venstre</td>
<td>109.1</td>
<td>4.8</td>
<td>4.4</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="limb-symmetry-index" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="limb-symmetry-index"><span class="header-section-number">3.5</span> Limb symmetry index</h3>
<p>“Limb symmetry index” (LSI) er et forholdstall mellom verdien til den svakere ekstremiteten og den sterkere ekstremiteten, multiplisert med 100 for å uttrykke forholdet som en prosent (Impellizeri et al., 2008). Følgende verdier blir kalkulert med formelen (svakere ben / sterkere ben) * 100 for hver test.</p>
<p>Ved pre-test, målte høyre og venstre ben symmetrisk maksimalt dreiemoment (LSI = 100% ved 60 °/s). Etter treningsperioden, ble styrkeforskjellen betraktelig større mellom høyre og venstre ben (LSI = 86,2% ved 60 °/s).</p>
</section>
</section>
<section id="diskusjon" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="diskusjon"><span class="header-section-number">4</span> Diskusjon</h2>
<p>Formålet med denne studien var å undersøke effekten av tre uker styrketrening på maksimalt dreiemoment i kneekstensjon hos en elitesprintsyklist. Resultatene viste en økning i maksimalt dreiemoment ved lav vinkelhastighet (60°/s), spesielt for høyre ben (+25,3 %), mens endringene ved høyere hastigheter (120°/s og 240°/s) var små eller negative. Disse funnene støtter delvis hypotesen om at styrketrening øker maksimal styrke, men effekten ser ut til å være spesifikk for lavere bevegelseshastigheter.</p>
<section id="sammenheng-med-tidligere-forskning" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="sammenheng-med-tidligere-forskning"><span class="header-section-number">4.1</span> Sammenheng med tidligere forskning</h3>
<p>Økningen i dreiemoment ved lav hastighet stemmer godt overens med tidligere studier som viser at tung styrketrening forbedrer maksimal muskelstyrke og kraftutvikling, (Rønnestad et al., 2010). Rønnestad et al.&nbsp;(2010) viste at veltrente syklister som kombinerte styrketrening med utholdenhetstrening økte både muskelstyrke og størrelse på quadriceps, i tillegg forbedret prestasjon relatert til sprint. Martin et al.&nbsp;(2007) fremhever at sprintsyklistens prestasjon er avhengig av samhandlingen mellom muskelkraft og bevegelseshastighet, og at økt maksimal kraft i kneekstensjon kan bidra til høyere akselerasjon og topphastighet i banen. Dermed kan styrke økningene ved 60°/s ha en overføringsverdi til akselerasjonsfasen i sprintsykling.</p>
<p>At økningene falt bort ved høyere vinkelhastigheter (120°/s og 240°/s) samsvarer med tidligere funn fra Dorel et al.&nbsp;(2005), som viste at sammenhengen mellom dreiemoment og hastighet er ikke-lineær, og at maksimalt dreiemoment reduseres når bevegelseshastigheten øker. For å forbedre prestasjon ved høyere hastigheter kreves ofte mer spesifikk trening som eksplosiv styrketrening, og hastighetsbasert styrke eller plyometriske øvelser (Cormie et al., 2011) (legg til denne i literrautlista)</p>
</section>
<section id="metodiske-styrker-og-begrensninger" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="metodiske-styrker-og-begrensninger"><span class="header-section-number">4.2</span> Metodiske styrker og begrensninger</h3>
<p>Reliabilitet handler om hvor pålitelig og konsistent et måleverktøy, altså om det gir samme resultat ved gjentatte tester under standardiserte forhold. HUMAC isokinetisk dynamometer har vist høy test–retest reliabilitet og intrarater reliabilitet ved måling av styrke i underekstremitetene. Og er kjent som gullstandarden (Stark et al., 2011). Dette betyr at apparatet kan gi stabile målinger under standardiserte forhold.</p>
<p>I denne casestudien ble det gjort seks tester med samme testleder, under standardiserte betingelser med lik oppvarming, samme tidspunkt på dagen og ernæring. Dette bidrar til høy intrarater reliabilitet.</p>
<p>Totalt sett viser analysen at deltakerens maksimale dreiemoment ble målt på en konsistent måte gjennom testene. Et moderat SD under 10 % anses som akseptabelt i isokinetiske tester (Hopkins, 2000), og funnene i denne studien støtter at målingene var både stabile og pålitelige gjennom hele testperioden.</p>
<p>Validitet refererer til hvor godt en test måler det den er ment å måle. HUMAC isokinetisk dynamometer har vist høy validitet for måling av muskelstyrke i underekstremitetene, noe som betyr at målingene reflekterer faktisk kraftproduksjon i muskelen.</p>
<p>I denne case-studien gir HUMAC mulighet til å registrere både små og store endringer i muskelstyrke over tid, slik som økningen i kneekstensjon på høyre ben ved 60°/s (+25,3 %). Selv om mindre endringer eller negative verdier kan forekomme. Slik som den observerte økningen i kneekstensjon på høyre ben. Variasjonen som ble observert, på venstre ben ved høyere, kan tilskrives biologisk variasjon, tretthet og rekkefølgen på testene, men det påvirker ikke validiteten til apparatet.</p>
<p>Variabilitet beskriver hvor mye måleresultatene sprer seg rundt et gjennomsnitt, og er en viktig faktor å vurdere når man tolker endringer i styrke over tid.</p>
<p>I denne case-studien med seks tester hos en elitesprint syklist var variasjonen størst på venstre bein ved høyere hastigheter, mens høyre bein viste relativt små variasjoner, spesielt ved 60°/s (+25,3 %). Dette indikerer at målingene på høyre bein hadde lavere intra-subjekt variabilitet, det kan hende venstre bein kan ha vært mer påvirket av at venstre beinet ble testet etter høyre i hver av seks testene.</p>
<p>Standardavvik (SD) og variasjonskoeffisient (CV) ble brukt for å vurdere konsistensen i målingene mellom testene for både høyre og venstre bein. SD gir et mål på den absolutte spredningen rundt gjennomsnittet, mens CV uttrykker denne spredningen relativt til gjennomsnittet.</p>
<p>Som vist i tabell 5, var både SD og CV generelt lave for begge bein, noe som indikerer at målingene var stabile og repeterbare. Dette tyder på høy reliabilitet i testprotokollen, spesielt ved hastigheter der CV var rundt 5 %. Enkelte hastigheter viste en noe høyere CV, noe som kan skyldes naturlige variasjoner i prestasjon, teknikk eller tretthet.</p>
<p>Likevel finnes det flere begrensninger. For det første ble studien gjennomført på én deltaker, noe som gjør resultatene ikke-generaliserbare. For det andre ble det ikke inkludert noen form kontrollgruppe, og eventuelle forbedringer kan være vanskelig å skille fra læringseffekten. Selv om deltager gjennomførte to tilvenningsøkter (Hopkins, 2000). I tillegg var intervensjonsperioden relativt kort (tre uker) og det gjør det vanskeligere å diktere forbedringer i styrke, det er sannsynlig at en lengre periode ville gitt større forbedringer og en bedre kraftproduksjon.</p>
</section>
</section>
<section id="referanseliste" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="referanseliste"><span class="header-section-number">5</span> Referanseliste</h2>
<p>Atkinson, G., &amp; Nevill, A. M. (1998). Statistical methods for assessing measurement error (reliability) in variables relevant to sports medicine. <em>Sports Medicine, 26</em>(4), 217–238. https://doi.org/10.2165/00007256-199826040-00002</p>
<p>Dorel S, Hautier CA, Rambaud O, Rouffet D, Van Praagh E, Lacour JR, Bourdin M. Torque and power-velocity relationships in cycling: relevance to track sprint performance in world-class cyclists. Int J Sports Med. 2005 Nov;26(9):739-46. doi: 10.1055/s-2004-830493. PMID: 16237619.</p>
<p>Hopkins WG. Measures of reliability in sports medicine and science. Sports Med. 2000 Jul;30(1):1-15. doi: 10.2165/00007256-200030010-00001. PMID: 10907753.</p>
<p>Impellizzeri, F. M., Bizzini, M., Rampinini, E., Cereda, F., &amp; Maffiuletti, N. A. (2008)<strong>.</strong> Reliability of isokinetic strength imbalance ratios measured using the Cybex NORM dynamometer. <em>Clinical Physiology and Functional Imaging, 28</em>(2), 113–119. https://doi.org/10.1111/j.1475-097X.2007.00786.x</p>
<p>Martin, J. C., Davidson, C. J., &amp; Pardyjak, E. R. (2007). Understanding sprint-cycling performance: The integration of muscle power, resistance, and modeling. <em>International Journal of Sports Physiology and Performance, 2</em>(1), 5-21. <a href="https://doi.org/10.1123/ijspp.2.1.5" class="uri">https://doi.org/10.1123/ijspp.2.1.5</a></p>
<p>Rønnestad BR, Hansen EA, Raastad T. Effect of heavy strength training on thigh muscle cross-sectional area, performance determinants, and performance in well-trained cyclists. Eur J Appl Physiol. 2010 Mar;108(5):965-75. doi: 10.1007/s00421-009-1307-z. Epub 2009 Dec 4. PMID: 19960350.</p>
<p>Stark, T., Walker, B., Phillips, J.K., Fejer, R., &amp; Beck, R. (2011). <em>Hand-held dynamometry correlation with the gold standard isokinetic dynamometry: A systematic review.</em> PM&amp;R, 3(5), 472-479. <a href="https://doi.org/10.1016/j.pmrj.2010.10.025" class="uri">https://doi.org/10.1016/j.pmrj.2010.10.025</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>